#Data Source Properties
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mofino?useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1324
#JPA Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=TRUE
spring.jpa.hibernate.ddl-auto=update

##CLOUD-SQL-CONFIGURATIONS
#spring.cloud.gcp.sql.database-name=mofino
#spring.cloud.gcp.sql.instance-connection-name=springbootonkubernettes:europe-west1:mofino
## So app starts despite "table already exists" errors.
#spring.datasource.continue-on-error=true
## Enforces database initialization
#spring.datasource.initialization-mode=always
##spring.datasource.username=test
##spring.datasource.password=12345
#spring.cloud.gcp.project-id=springbootonkubernettes
#spring.cloud.gcp.credentials.location=/src/main/resources/springbootonkubernettes-0a877356fde8.json